cc_library(
    name = "scenes",
    srcs = [
        "checkered_spheres_scene.h",
        "cornell_box_scene.h",
        "earth_scene.h",
        "perlin_spheres_scene.h",
        "quads_scene.h",
        "random_sphere_scene.h",
        "simple_light_scene.h",
        "three_orb_scene.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//extras:rtweekend",
        "//hittables",
        "//materials",
        "//textures",
    ],
)
