cc_library(
    name = "hittables",
    srcs = [
        "bvh.h",
        "hittable.h",
        "hittable_list.h",
        "quad.h",
        "sphere.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//extras:rtweekend",
        "//materials",
    ],
)
