cc_library(
    name = "math_structures",
    srcs = [
        "aabb.h",
        "color.h",
        "interval.h",
        "onb.h",
        "ray.h",
        "vec3.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//extras:rtweekend"],
)
