cc_library(
    name = "perlin",
    srcs = ["perlin.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "rtweekend",
    srcs = [
        "rtw_stb_image.h",
        "rtweekend.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["stb-image"],
)

cc_library(
    name = "stb-image",
    srcs = [
        "stb_image.h",
    ],
    visibility = ["//visibility:public"],
)
