cc_library(
    name = "materials",
    srcs = [
        "dielectric.h",
        "lambertian.h",
        "material.h",
        "metal.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//math_structures",
        "//textures",
    ],
)
